name: test, build, push and deploy
on:
  push:
    branches: [ "5", "k8s" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test
      env:
        CI: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: public-transport/kubernetes-setup/deploy-basic-service@gh-action
      with:
        docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        kubernetes-config: ${{ secrets.KUBERNETES_CONFIG }}
